### ISSUE TITLE
Stuck tiles after opening mines

### ISSUE THREAD

**Issue by IBPX** [kudima/minesweeper#7]
I've had an issue where mines will get stuck "half-open", then they can't be opened, rendering a game uncompletable. I haven't quite figured it out, but here's the closest I've found to recreating it:

![Example](https://user-images.githubusercontent.com/5852398/36359929-8d4bade0-1517-11e8-8d37-df46faf73521.png)

Flag a tile, and keeping your mouse there, hold down left click, then quickly move it to another tile and let go. This only works once every maybe five tries.

**Comment by kudima** [comment]
Can you, please, clarify what do you mean by "rendering a game uncompletable"? By doing what I managed to conclude from the description I only got to the following situation. If you flag a tile, and then open one of the surrounding tiles, which happens to have no bombs around, the game only opens that specific tile, but does the flip the neighbouring tiles with  zero bombs around. In this case I still could continue to play the game normally.

**Comment by IBPX** [comment]
The tile doesn't open but instead becomes unopenable, so it's impossible to finish the game. I've explained it badly because I haven't quite figured out how it works, so my explanation only works once every handful of tries (usually it just opens the tile regularly, the expected behavior).

Notice the stuck tile in the image is not the same color as a regular open tile.

**Comment by kudima** [comment]
I've created a new branch issue7, removing the behavior I managed to get with your description. Can you please check if you can reproduce the issue on that branch?

**Comment by IBPX** [comment]
That seems to have fixed it. (Fixed #7)

**Comment by IBPX** [comment]
That seems to have fixed it. Thanks.
